//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebService.TestSendEmail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://contact.di.webservice.huiyee.com/", ConfigurationName="TestSendEmail.SendEmailSoap")]
    public interface SendEmailSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contact.di.webservice.huiyee.com/postxml", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        string postxml(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://contact.di.webservice.huiyee.com/postxml", ReplyAction="*")]
        System.Threading.Tasks.Task<string> postxmlAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendEmailSoapChannel : TestWebService.TestSendEmail.SendEmailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendEmailSoapClient : System.ServiceModel.ClientBase<TestWebService.TestSendEmail.SendEmailSoap>, TestWebService.TestSendEmail.SendEmailSoap {
        
        public SendEmailSoapClient() {
        }
        
        public SendEmailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendEmailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendEmailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string postxml(string xml) {
            return base.Channel.postxml(xml);
        }
        
        public System.Threading.Tasks.Task<string> postxmlAsync(string xml) {
            return base.Channel.postxmlAsync(xml);
        }
    }
}
